apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: nginx-ds
   labels:
      env: demo
spec:
  template:
    metadata:
      name: nginx
      labels:
        env: demo
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80 
  selector:
    matchLabels:
      env: demo
