apiVersion: apps/v1
kind: deployment
metadata:
   name: nginx-deployment
   labels:
      env: demo
spec:
  template:
    metadata:
      name: nginx
      labels:
        env: demo
    spec:
      containers:
      - image: nginx
        name: nginx
  replicas: 3
  selector:
    matchLabels:
      env: demo
